### ISSUE TITLE
or_migrate fails to import calendar entries correctly

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/openreception#12]
When trying to edit/delete an imported calendar entry, the server_stack fails and return a 500.

**Comment by rostgaard** [comment]
This is actually an or_migrate issue. The tool does not commit the imported calendar entries to the filestore, so the git command fail.
It can be remedied, until fixed, by cd'ing to the filestore root and running

`git add .`
`git commit --author="System <system@openreception>" -m "uid:0 - Import"`

Note: This will add various files that are not intended to be under revisioning. However, it will do no harm if they are.
