### ISSUE TITLE
Rid from reception_client is occasionally noId

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/openreception#4]
Clients sometimes end up in a situation where they can't save/send messages due to a cross-origin error. The server simply returns 500 with a cross-origin error notice.

There's not apparent pattern to this and it goes away after a client refresh.

**Comment by rostgaard** [comment]
I seem to recall to have tracked this down earlier. It seems to be caused by an odd client-state-bug, where the reception-id is not set.
This causes a server-side exception, triggered by a db-key constraint - which is then caught by the shelf default exception handler (that has no method for installing CORS headers).

shelf_exception_response is incompatible with our current pubspec.

**Comment by ThomasLocke** [comment]
We fixed the old bus/async code, so it is now straight up synchronous. On send we simply query the DOM for the currently selected reception and contact. If we fail on getting the reception/contact id, then it means a simple DOM query of _list.querySelector('.selected') have failed, which seems highly unlikely.

So if the client-state-bug ever existed, it for sure does not exist now, unless of course it can be attributed to a failing DOM query.

**Comment by rostgaard** [comment]
The error from the message server is:
`SqlError: pgpool1:1420:23470 ERROR 23502 null value in column "context_reception_name" violates not-null constraint`
Which aries from the
`context_reception_id: 0, context_contact_name: Blanked, context_reception_name: null`
in the supplied parameters.
All the message server does is:
```
      content = await request.readAsString();
      message = new Model.Message.fromMap(JSON.decode(content))
        ..senderId = user.id;
```
So If bad values are null and 0, then they are almost certainly set that way by the client. As the message-parameter harvesting happens independently from reception selection, then it is potentially possible to unset a reception _before_ the message harvesting is done. Other than that, a failing DOM query is my only guess :-\

**Comment by ThomasLocke** [comment]
/me cries

Luckily we don't have to rely on the DOM query. We have other means of obtaining the necessary id's.

**Comment by rostgaard** [comment]
The strange thing is that the contact id is fine.
