### ISSUE TITLE
"Lag" issue if creation of agent channel fails due to loss of connection to SNOM

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/openreception#5]
Note the word "potential". I have no idea if these things are even connected, but we've had one issue where callflow reported failure to create an agent channel, and after the fact multiple agents reported sluggish performance when answering/redirecting/park/unpark calls.

**Comment by rostgaard** [comment]
Added the test. Confirmed that this is indeed a bug. Removing "potential" word, as this is now the real deal.
